version: '3.8'

services:
    extrapolation:
        build:
            context: extrapolation
            network: host
        volumes:
            - type: bind
              source: ./data
              target: /data
        user: ${USER_ID}
        network_mode: host

    scraper:
        build:
            context: scraper
            network: host
        volumes:
            - type: bind
              source: ./data
              target: /input-data
            - type: bind
              source: ./data
              target: /output-data
        user: ${USER_ID}
        network_mode: host

    downloader:
        build:
            context: downloader
            network: host
        volumes:
            - type: bind
              source: ./data
              target: /data
        user: ${USER_ID}
        network_mode: host
