name: Data Update

on:
  branches:
    - master

jobs:
  name: Update
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: LS test
      run: ls -alh ./
    - name: Update Data
      uses: ./.github/actions/update-data-action
