name: Data Update

on:
  push:
    branches:
    - master
  schedule:
    - cron: '30 12-15,23 * * *'

jobs:
  update-data-job:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Data
        uses: ./.github/actions/update-data-action
      - name: Scrape Data
        uses: ./.github/actions/scrape-action
      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          add: data/csv/chapeco.csv
          author_name: Diego Pereira
          author_email: rockin.jack@gmail.com
          message: 'Auto data update'
          tag: 'latest-data'
          force: true
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.0.5 # This is the action
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "covid19-xap"
            heroku_email: "rockin.jack@gmail.com"
