name: Data Update

on: [push]

jobs:
  update-data-job:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: LS test
        run: ls -alh ./
      - name: Update Data
        uses: ./.github/actions/update-data-action
      - name: Scrape Data
        uses: ./.github/actions/scrape-action
